from openai.api_resources.audio import Audio  
from openai.api_resources.chat_completion import ChatCompletion  
from openai.api_resources.completion import Completion  
from openai.api_resources.customer import Customer  
from openai.api_resources.deployment import Deployment  
from openai.api_resources.edit import Edit  
from openai.api_resources.embedding import Embedding  
from openai.api_resources.engine import Engine  
from openai.api_resources.error_object import ErrorObject  
from openai.api_resources.file import File  
from openai.api_resources.fine_tune import FineTune  
from openai.api_resources.image import Image  
from openai.api_resources.model import Model  
from openai.api_resources.moderation import Moderation  
